name: dev_eza_api
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  dio: 4.0.1
  json_annotation: 4.3.0
  json_serializable: 6.0.1
  injectable: ^1.5.0
  get_it: 7.2.0
  injectable_generator: 1.5.0
  build_runner: 2.1.5
  dotenv: 3.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0

assets:
  .env